name: CICD

on: 
  push: 
    branches: [main]

jobs:
  build:
   runs-on: [ubuntu-latest] 
   steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t integrationtest/nodejs-app .

      - name: Push image to docker hub
        run: docker push strapi-image/my-project .

      - name: Publish image to docker hub
        run: docker push strapi-image/my-project:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub    
        run: docker pull strapi-image/my-project:latest
      - name: Delete old container
        run: docker rm -f my-project-container
      - name: Run docker container
        run: docker run -d -p 1337:1337 -name my-project-container strapi-image/my-project  


