name: CICD

on: 
  push: 
    branches: [main]

jobs:
  build:
   runs-on: [ubuntu-latest] 
   steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t strapi-image .

      - name: Image tag
        run: docker tag strapi-image ${{ secrets.DOCKER_USERNAME }}/strapi-image  

      - name: Publish image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/strapi-image

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub    
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/strapi-image:latest
      - name: Run docker container
        run: docker run -d -p 1337:1337 --name my-project-container ${{ secrets.DOCKER_USERNAME }}/strapi-image


